name: Terraform EC2 Instance

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify Terraform Directory
        run: ls -al ./terraform

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Terraform plan
        id: plan
        run: |
          set +e
          terraform plan -detailed-exitcode -input=false -out=tfplan
          exit_code=$?
          set -e
          if [ $exit_code -eq 2 ]; then
            echo "There are pending changes."
            exit 0
          elif [ $exit_code -eq 0 ]; then
            echo "No changes detected in the Terraform plan."
            exit 0
          else
            echo "Terraform plan failed."
            exit 1
          fi

      - name: Show Terraform Plan
        run: terraform show -json tfplan
        working-directory: ./terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -auto-approve tfplan -input=false -no-color
          echo "apply_output=$(terraform output -json)" >> $GITHUB_STATE
          echo "apply_output=$(terraform output -json)" >> $GITHUB_OUTPUT
        working-directory: ./terraform
